# Config file for the Auto Mapping ROS node

# Parameter for pure pursuit algorithm
# A good estimate is 0-2r (According to the implementation explanation given in RI, CMU)
lookahead_distance : 2.0

# Map Resolution (meters/pixel)
resolution : 0.05