# Config file for the Auto Mapping ROS node

# Parameter for pure pursuit algorithm
# A good estimate is 0-2r (According to the implementation explanation given in RI, CMU)
lookahead_distance : 0.8

# Map Resolution (meters/pixel)
resolution : 0.05

# Distance threshold to start planning for the next node
distance_threshold : 3.0