global_frame: map
robot_base_frame: base_ABot
update_frequency: 1.0
static_map: true
rolling_window: false
track_unknown_space: true
allow_unknown: true
resolution: 0.05

#inflation_global:
#    inflation_radius: 0.25

plugins:
#  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_global,               type: "costmap_2d::InflationLayer"}
