global_frame: map
robot_base_frame: base_ABot
update_frequency: 5.0
publish_frequency: 1.0
static_map: true
rolling_window: true
resolution: 0.025
allow_unknown: true

#inflation:
#    inflation_radius: 0.2

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

